App\Entity\Author:
    properties:
        name:
            - NotNull: ~
            - Length:
                max: 64
            - Type:
                type: string
                message: The value {{ value }} is not a valid {{ type }

App\Entity\Category:
    properties:
        title:
            - NotNull: ~
            - Length:
                max: 64
            - Type:
                type: string
                message: The value {{ value }} is not a valid {{ type }

App\Entity\Comment:
    properties:
        title:
        -   NotNull: ~
        -   Length:
                max: 160
        -   Type:
                type: string
                message: The value {{ value }} is not a valid {{ type }
        body:
            - NotNull: ~
            - Length:
                max: 1024
            - Type:
                type: string
                message: The value {{ value }} is not a valid {{ type }

App\Entity\Tag:
    properties:
        title:
            - NotNull: ~
            - Length:
                max: 64
            - Type:
                type: string
                message: The value {{ value }} is not a valid {{ type }

App\Entity\Post:
    properties:
        title:
            - NotNull:
            - Type:
                type: string
                message: The value {{ value }} is not a valid {{ type }}
        description:
            - NotBlank: ~
            - Length:
                min: 65
                max: 120
                minMessage: 'Your description must be at least {{ limit }} characters long'
                maxMessage: 'Your description cannot be longer than {{ limit }} characters'
        body:
            - NotNull: ~
            - Length:
                min: 350
                max: 2024
                minMessage: 'Your text of post must be at least {{ limit }} characters long'
                maxMessage: 'Your text of post  cannot be longer than {{ limit }} characters'
        status:
            - NotNull: ~
