App\Entity\Comment:
    properties:
        title:
            - NotNull: ~
            - Length:
                max: 160
            - Type:
                type: string
        body:
            - NotNull: ~
            - Length:
                max: 1024
            - Type:
                type: string
