index:
    path: /
    controller: App\Controller\PostController::index

blog:
    path: /blog
    controller: App\Controller\PostController::index

post_new:
    path: /post/new
    controller: App\Controller\PostController::new

post_show:
    path: /post/{slug}
    controller: App\Controller\PostController::show

post_delete:
    path: /post/{slug}/delete
    controller: App\Controller\PostController::delete

author_new:
    path: /author/new
    controller: App\Controller\AuthorController::new

author_edit:
    path: /author/edit/{id}
    controller: App\Controller\AuthorController::edit

authors:
    path: /authors
    controller: App\Controller\AuthorController:index

post_edit:
    path: /post/edit/{slug}
    controller: App\Controller\PostController::edit

category_new:
    path: /category/new
    controller: App\Controller\CategoryController::new

category_edit:
    path: /category/edit/{slug}
    controller: App\Controller\CategoryController::edit

categories:
    path: /categories
    controller: App\Controller\CategoryController::index

category_show:
    path: /category/{slug}
    controller: App\Controller\CategoryController::index

comment_new:
    path: /comment/{postSlug}/new
    controller: App\Controller\PostController::commentNew

tag_new:
    path: /tag/new
    controller: App\Controller\TagController::new

tag_show:
    path: /tag/{slug}
    controller: App\Controller\TagController::index

tags:
    path: /tags
    controller: App\Controller\TagController::index

tag_edit:
    path: /tag/edit/{slug}
    controller: App\Controller\TagController::edit

logout:
    path: /logout

login:
    path: /login
    controller: App\Controller\SecurityController::login
