#index:
#    path: /
#    controller: App\Controller\DefaultController::index

blog:
    path: /blog
    controller: App\Controller\PostController::index

post_new:
    path: /post/new
    controller: App\Controller\PostController::new

post_show:
    path: /post/{slug}
    controller: App\Controller\PostController::show

author_new:
    path: /author/new
    controller: App\Controller\AuthorController::new

author_show:
    path: /author/{slug}
    controller: App\Controller\AuthorController::index

post_edit:
    path: /post/edit/{slug}
    controller: App\Controller\PostController::edit

category_new:
    path: /category/new
    controller: App\Controller\CategoryController::new

category_show:
    path: /category/{slug}
    controller: App\Controller\CategoryController::index

comment_new:
    path: /comment/new
    controller: App\Controller\CommentController::new

comment_show:
    path: /comment/{slug}
    controller: App\Controller\CommentController::index

tag_new:
    path: /tag/new
    controller: App\Controller\TagController::new

tag_show:
    path: /tag/{slug}
    controller: App\Controller\TagController::index
