index:
    path: /{_locale}/{count<\d+>}
    controller: App\Controller\PostController::index
    defaults:   { _locale: en, count: 10 }
    options:
        sitemap: true
    requirements:
        _locale:  en|uk

post_show:
    path: /{_locale}/post/{slug}
    controller: App\Controller\PostController::show

category_posts:
    path: /{_locale}/{categorySlug}/posts/{count<\d+>}
    controller: App\Controller\CategoryController::getCategoryPosts
    defaults:   { count: 10 }
    requirements:
        _locale:  en|uk

comment_new:
    path: /{_locale}/comment/{postSlug}/new
    controller: App\Controller\PostController::commentNew
    requirements:
        _locale:  en|uk

logout:
    path: /logout

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications

send_notification:
    path: /send-notification
    controller: App\Controller\PostController::sendNotification

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

redcode_tree:
    resource: "@RedCodeTreeBundle/Resources/config/routing.yml"
    prefix:   /admin

app.swagger_ui:
    path: /api-doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api-doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

api:
    path: /api
    controller: App\Controller\Api\SecurityController::api

api_login_check:
    path:     /api/login
    methods:  POST

gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

search:
    path: /{_locale}/search
    controller: App\Controller\SearchController::index
    requirements:
        _locale:  en|uk
